name: Run Cypress Tests

on:
  workflow_call:
    inputs:
      ENV:
        required: false
        default: 'dev'
        type: string
      EC2_INSTANCE_TYPE:
        default: 't3a.large'
        required: false
        type: string
      CYPRESS_DIR:
        default: 'cypress'
        type: string
      APP_DIR:
        default: '.'
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GH_RUNNER_TOKEN:
        required: true

      CYPRESS_RECORD_KEY:
        required: true

      AWS_REGION:
        required: true
      AWS_IAM_ROLE:
        required: false
      EC2_IMAGE:
        required: true
      EC2_SUBNET:
        required: true
      EC2_SECURITY_GROUP:
        required: true
      EC2_IAM_ROLE:
        required: true
      S3_BUCKET:
        required: true

jobs:
  start-runner:
    name: Runner
    uses: globalopsteam/workflows/.github/workflows/start-runner.yml@master
    with:
      EC2_INSTANCE_TYPE: ${{ inputs.EC2_INSTANCE_TYPE }}
      RUNNER_COUNT: 3
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_RUNNER_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}

      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
      EC2_IMAGE: ${{ secrets.EC2_IMAGE }}
      EC2_SUBNET: ${{ secrets.EC2_SUBNET }}
      EC2_SECURITY_GROUP: ${{ secrets.EC2_SECURITY_GROUP }}
      EC2_IAM_ROLE: ${{ secrets.EC2_IAM_ROLE }}

  cypress-setup:
    name: Setup
    needs:
      - start-runner
    runs-on: ${{ needs.start-runner.outputs.ec2-instance-id }}
    steps:
      - name: Fetch docker image
        run: |
          docker pull "cypress/included:10.10.0"

  cypress-run:
    name: Run
    needs:
      - start-runner
      - cypress-setup
    runs-on: ${{ needs.start-runner.outputs.ec2-instance-id }}
    container: cypress/included:10.10.0
    strategy:
      fail-fast: false
      matrix:
        browser: ['electron', 'chrome', 'firefox']
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'
          ref: ${{ github.event_name != 'schedule' && github.ref || inputs.ENV == 'prod' && 'refs/heads/production' || 'refs/heads/dev' }}
          token: ${{ secrets.GH_RUNNER_TOKEN }}

      - name: Configure Environment
        id: env_setup
        env:
          APP_DIR: "${{ inputs.APP_DIR }}"
          EVENT_NAME: "${{ github.event_name }}"
          ENV: "${{ inputs.env }}"
          REPO: "${{ github.repository }}"
        run: |
          echo repo=$(basename "${REPO}" | sed 's/^docker-//') >> "${GITHUB_OUTPUT}"
          echo branch=$(git -C "${APP_DIR}" rev-parse --abbrev-ref HEAD) >> "${GITHUB_OUTPUT}"
          echo subject=$([ "$EVENT_NAME" == "schedule" ] && echo -n "Scheduled Tests $(date -u +%Y-%m-%d)_$(($(date -u +%H) / 6 + 1)):" || echo "${ENV}:") $(git -C "${APP_DIR}" log -n1 --format="%s") >> "${GITHUB_OUTPUT}"
          git -C "${APP_DIR}" log -n1 --format="author=%an%nemail=%ae%nhash=%H%ntime=%ct" >> "${GITHUB_OUTPUT}"
          echo remote=$(git -C "${APP_DIR}" config --get remote.origin.url) >> "${GITHUB_OUTPUT}"

      - name: Fetch cypress environment json
        run: |
          aws s3 cp "s3://${{ secrets.S3_BUCKET }}/${{ inputs.ENV }}/${{ steps.env_setup.outputs.repo }}/cypress.env.json" "${{ inputs.CYPRESS_DIR }}/cypress.env.json"

      - name: Cypress Run
        uses: cypress-io/github-action@v4
        with:
          browser: ${{ matrix.browser }}
          record: true
          parallel: true
          working-directory: ${{ inputs.CYPRESS_DIR }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COMMIT_INFO_BRANCH: ${{ steps.env_setup.outputs.branch != 'HEAD' && steps.env_setup.outputs.branch || inputs.ENV == 'prod' && 'production' || inputs.ENV == 'stage' && 'master' || inputs.env == 'dev' && 'dev' || github.ref_name }}
          COMMIT_INFO_MESSAGE: ${{ steps.env_setup.outputs.subject }}
          COMMIT_INFO_AUTHOR: ${{ steps.env_setup.outputs.author }}
          COMMIT_INFO_EMAIL: ${{ steps.env_setup.outputs.email }}
          COMMIT_INFO_SHA: ${{ steps.env_setup.outputs.hash }}
          COMMIT_INFO_TIMESTAMP: ${{ steps.env_setup.outputs.time }}
          COMMIT_INFO_REMOTE: ${{ steps.env_setup.outputs.remote }}

  stop-runner:
    name: Runner
    needs:
      - start-runner     # required to get output from the start-runner job
      - cypress-setup
      - cypress-run
    if: always() && needs.start-runner.outputs.ec2-instance-id != '' # required to stop the runner even if the error happened in the previous jobs
    uses: globalopsteam/workflows/.github/workflows/stop-runner.yml@master
    with:
      EC2_INSTANCE_ID: ${{ needs.start-runner.outputs.ec2-instance-id }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_IAM_ROLE: ${{ secrets.AWS_IAM_ROLE }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      GH_RUNNER_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
