name: Build docker image and push to registry

on:
  workflow_call:
    inputs:
      IMAGE_REPOSITORY:
        required: true
        type: string

    secrets:
      REGISTRY_ADDRESS:
        required: true
      REGISTRY_USERNAME:
        required: true
      REGISTRY_PASSWORD:
        required: true
      PIP_EXTRA_INDEX_URL:
        required: false
      GH_RUNNER_TOKEN:
        required: false

jobs:
  build-push:
    name: Build + Push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout recursive submodules with GH_RUNNER_TOKEN
        uses: actions/checkout@v3
        env:
          GH_RUNNER_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
        if: env.GH_RUNNER_TOKEN != null
        with:
          token: ${{ secrets.GH_RUNNER_TOKEN }}
          submodules: "recursive"

      - name: Checkout without GH_RUNNER_TOKEN
        uses: actions/checkout@v3
        env:
          GH_RUNNER_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
        if: env.GH_RUNNER_TOKEN == null
        with:
          submodules: "recursive"

      - name: Get the branch or tag name and set the environment
        id: branch-tag
        run: |
          echo "Git ref: $GITHUB_REF"
          if [[ "$GITHUB_REF" == refs/heads/* ]]; then
            BRANCH_NAME=${GITHUB_REF#refs/heads/}
            echo "This is a branch: $BRANCH_NAME"
            echo "branch=$BRANCH_NAME" >> $GITHUB_OUTPUT
            echo "env=$BRANCH_NAME" >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_REF" == refs/tags/* ]]; then
            TAG_NAME=${GITHUB_REF#refs/tags/}
            echo "This is a tag: $TAG_NAME"
            echo "tag=$TAG_NAME" >> $GITHUB_OUTPUT
            echo "env=tag-${TAG_NAME}" >> $GITHUB_OUTPUT
          fi

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${{ steps.branch-tag.outputs.env }}-${sha}-${ts}"

      - name: Login to Docker registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_ADDRESS }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Determine initial image tags
        id: determine-image-tags
        env:
          IMAGE_REPOSITORY: ${{ inputs.IMAGE_REPOSITORY }}
          REGISTRY_ADDRESS: ${{ secrets.REGISTRY_ADDRESS }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          echo "tag=$REGISTRY_ADDRESS/$IMAGE_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "branch=$REGISTRY_ADDRESS/$IMAGE_REPOSITORY:${{ steps.branch-tag.outputs.env }}" >> $GITHUB_OUTPUT
          echo "latest=$REGISTRY_ADDRESS/$IMAGE_REPOSITORY:latest" >> $GITHUB_OUTPUT
          echo "build_id=$REGISTRY_ADDRESS/$IMAGE_REPOSITORY:${{ steps.prep.outputs.BUILD_ID }}" >> $GITHUB_OUTPUT

      - name: Build image
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        env:
          IMAGE_FULL_TAG_SHA: ${{ steps.determine-image-tags.outputs.tag }}
          IMAGE_FULL_TAG_BRANCH: ${{ steps.determine-image-tags.outputs.branch }}
          IMAGE_FULL_TAG_LATEST: ${{ steps.determine-image-tags.outputs.latest }}
          IMAGE_FULL_TAG_BUILD_ID: ${{ steps.determine-image-tags.outputs.build_id }}
          REGISTRY_ADDRESS: ${{ secrets.REGISTRY_ADDRESS }}
          ENV: ${{ steps.branch-tag.outputs.env }}
        run: |
          docker build --build-arg "REGISTRY_ADDRESS=${REGISTRY_ADDRESS}" --build-arg "ENV=${ENV}" --build-arg "PIP_EXTRA_INDEX_URL=${{ secrets.PIP_EXTRA_INDEX_URL }}" -t "${IMAGE_FULL_TAG_SHA}" -t "${IMAGE_FULL_TAG_BRANCH}" -t "${IMAGE_FULL_TAG_BUILD_ID}" -t "${IMAGE_FULL_TAG_LATEST}" .

      - name: Push image to Docker Registry
        if: github.event_name == 'push'
        env:
          IMAGE_FULL_TAG: ${{ steps.determine-image-tags.outputs.tag }}
        run: |
          docker push "${IMAGE_FULL_TAG} --all-tags"
