name: Build docker image and push to AWS ECR

on:
  workflow_call:
    inputs:
      ENV:
        required: false
        default: "dev"
        type: string
      ECR_REPOSITORY:
        required: true
        type: string
      UPDATE_SUBMODULE:
        required: false
        # lol, type isn't supported for inputs, this is a string, whatever
        default: true
        type: boolean

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_REGION:
        required: true
      PIP_EXTRA_INDEX_URL:
        required: false
      GH_RUNNER_TOKEN:
        required: false

jobs:
  build-push:
    name: Build + Push
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout recursive submodules with GH_RUNNER_TOKEN
        uses: actions/checkout@v3
        env:
          GH_RUNNER_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
        if: env.GH_RUNNER_TOKEN != null
        with:
          token: ${{ secrets.GH_RUNNER_TOKEN }}
          submodules: "recursive"

      - name: Checkout without GH_RUNNER_TOKEN
        uses: actions/checkout@v3
        env:
          GH_RUNNER_TOKEN: ${{ secrets.GH_RUNNER_TOKEN }}
        if: env.GH_RUNNER_TOKEN == null
        with:
          submodules: "recursive"

      - name: Generate build ID
        id: prep
        run: |
          branch=${GITHUB_REF##*/}
          sha=${GITHUB_SHA::8}
          ts=$(date +%s)
          echo "::set-output name=BUILD_ID::${branch}-${sha}-${ts}"

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Amazon ECR
        id: setup-ecr
        env:
          ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          aws ecr create-repository --repository-name "${ECR_REPOSITORY}" || true
          MANIFEST=$(aws ecr batch-get-image --repository-name "${ECR_REPOSITORY}" --image-ids "imageTag=${IMAGE_TAG}" --query images[].imageManifest --output text)
          { [[ -n "${MANIFEST}" ]] && echo "exists=true" || echo "exists=false"; } >> $GITHUB_OUTPUT
          echo "tag=$ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG" >> $GITHUB_OUTPUT
          echo "branch=$ECR_REGISTRY/$ECR_REPOSITORY:${{ inputs.ENV }}" >> $GITHUB_OUTPUT
          echo "latest=$ECR_REGISTRY/$ECR_REPOSITORY:latest" >> $GITHUB_OUTPUT

      - name: Build image
        if: github.event_name == 'pull_request' || github.event_name == 'push'
        env:
          IMAGE_FULL_TAG: ${{ steps.setup-ecr.outputs.tag }}
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ENV: ${{ inputs.ENV }}
        run: |
          docker build --build-arg "ECR_REGISTRY=${ECR_REGISTRY}" --build-arg "ENV=${ENV}" --build-arg "PIP_EXTRA_INDEX_URL=${{ secrets.PIP_EXTRA_INDEX_URL }}" -t "${IMAGE_FULL_TAG}" .

      - name: Push image to Amazon ECR
        if: github.event_name == 'push'
        env:
          IMAGE_FULL_TAG: ${{ steps.setup-ecr.outputs.tag }}
        run: |
          docker push "${IMAGE_FULL_TAG}"

      - name: Tag image in Amazon ECR
        if: github.event_name == 'push'
        env:
          IMAGE_TAG: ${{ github.sha }}
          ECR_REPOSITORY: ${{ inputs.ECR_REPOSITORY }}
        run: |
          MANIFEST=$(aws ecr batch-get-image --repository-name "${ECR_REPOSITORY}" --image-ids "imageTag=${IMAGE_TAG}" --query images[].imageManifest --output text)
          aws ecr put-image --repository-name "${ECR_REPOSITORY}" --image-tag "${{ inputs.ENV }}" --image-manifest "${MANIFEST}" > /dev/null || true
          aws ecr put-image --repository-name "${ECR_REPOSITORY}" --image-tag "latest" --image-manifest "${MANIFEST}" > /dev/null || true
          aws ecr put-image --repository-name "${ECR_REPOSITORY}" --image-tag "${{ steps.prep.outputs.BUILD_ID }}" --image-manifest "${MANIFEST}" > /dev/null || true
