name: Start EC2 GitHub runner instance

on:
  workflow_call:
    inputs:
      EC2_INSTANCE_TYPE:
        required: true
        type: string
      RUNNER_COUNT:
        required: false
        default: 1
        type: number

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GH_RUNNER_TOKEN:
        required: true

      AWS_REGION:
        required: true
      AWS_IAM_ROLE:
        required: false
      EC2_IMAGE:
        required: true
      EC2_SUBNET:
        required: true
      EC2_SECURITY_GROUP:
        required: true
      EC2_IAM_ROLE:
        required: true

    outputs:
      ec2-instance-id:
        description: "GitHub Runner EC2 Instance ID"
        value: ${{ jobs.start-runner.outputs.ec2-instance-id }}

jobs:
  start-runner:
    name: Start
    runs-on: ubuntu-latest
    outputs:
      ec2-instance-id: ${{ steps.start-ec2-runner.outputs.ec2-instance-id }}
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-duration-seconds: 3600
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Start EC2 runner
        id: start-ec2-runner
        uses: globalopsteam/ec2-github-runner@v2-na-new
        with:
          mode: start
          github-token: ${{ secrets.GH_RUNNER_TOKEN }}
          ec2-image-id: ${{ secrets.EC2_IMAGE }}
          ec2-instance-type: ${{ inputs.EC2_INSTANCE_TYPE }}
          subnet-id: ${{ secrets.EC2_SUBNET }}
          security-group-id: ${{ secrets.EC2_SECURITY_GROUP }}
          iam-role-name: ${{ secrets.EC2_IAM_ROLE }}
          runner-tar-file: /root/actions-runner-linux-x64-2.298.2.tar.gz
          runner-count: ${{ inputs.RUNNER_COUNT }}
          aws-resource-tags: >
            [
              {"Key": "Name", "Value": "github-runner"},
              {"Key": "Service", "Value": "ec2-github-runner"},
              {"Key": "GitHubRepository", "Value": "${{ github.repository }}"},
              {"Key": "GitHash", "Value": "${{ github.sha }}"}
            ]

