name: Stop EC2 GitHub runner instance

on:
  workflow_call:
    inputs:
      EC2_INSTANCE_ID:
        required: true
        type: string
      RUNNER_LABEL:
        required: true
        type: string

    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      GH_RUNNER_TOKEN:
        required: true

      AWS_REGION:
        required: true
      AWS_IAM_ROLE:
        required: false

jobs:
  stop-runner:
    name: Stop
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          role-to-assume: ${{ secrets.AWS_IAM_ROLE }}
          role-duration-seconds: 3600
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Stop EC2 runner
        uses: globalopsteam/ec2-github-runner@v2-na
        with:
          mode: stop
          github-token: ${{ secrets.GH_RUNNER_TOKEN }}
          label: ${{ inputs.RUNNER_LABEL }}
          ec2-instance-id: ${{ inputs.EC2_INSTANCE_ID }}
